"""Add date field to Transaction model

Revision ID: 748149a65aed
Revises: 4fe45021f07f
Create Date: 2024-09-05 23:50:40.818681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748149a65aed'
down_revision = '4fe45021f07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
