"""Update transaction model to include recipient and sender account numbers

Revision ID: de2a6fe21beb
Revises: 748149a65aed
Create Date: 2024-09-06 00:19:24.642494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2a6fe21beb'
down_revision = '748149a65aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_account_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_account_number', sa.Integer(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('sender_account_number')
        batch_op.drop_column('recipient_account_number')

    # ### end Alembic commands ###
